#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbImporter.Future.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="STOCK_TW")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRowContract_ID(RowContract_ID instance);
    partial void UpdateRowContract_ID(RowContract_ID instance);
    partial void DeleteRowContract_ID(RowContract_ID instance);
    partial void InsertRowTradeInf(RowTradeInf instance);
    partial void UpdateRowTradeInf(RowTradeInf instance);
    partial void DeleteRowTradeInf(RowTradeInf instance);
    partial void InsertRowCorpX3(RowCorpX3 instance);
    partial void UpdateRowCorpX3(RowCorpX3 instance);
    partial void DeleteRowCorpX3(RowCorpX3 instance);
    partial void InsertRowBigTraderUnclosedVol(RowBigTraderUnclosedVol instance);
    partial void UpdateRowBigTraderUnclosedVol(RowBigTraderUnclosedVol instance);
    partial void DeleteRowBigTraderUnclosedVol(RowBigTraderUnclosedVol instance);
    #endregion
		
		public DbDataContext() : 
				base(global::DbImporter.Properties.Settings.Default.STOCK_TWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RowContract_ID> RowContract_IDs
		{
			get
			{
				return this.GetTable<RowContract_ID>();
			}
		}
		
		public System.Data.Linq.Table<RowTradeInf> RowTradeInfs
		{
			get
			{
				return this.GetTable<RowTradeInf>();
			}
		}
		
		public System.Data.Linq.Table<RowCorpX3> RowCorpX3s
		{
			get
			{
				return this.GetTable<RowCorpX3>();
			}
		}
		
		public System.Data.Linq.Table<RowBigTraderUnclosedVol> RowBigTraderUnclosedVols
		{
			get
			{
				return this.GetTable<RowBigTraderUnclosedVol>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contract_ID")]
	public partial class RowContract_ID : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private byte _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDChanging(byte value);
    partial void OnIDChanged();
    #endregion
		
		public RowContract_ID()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="TinyInt NOT NULL")]
		public byte ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FutureTradeInf")]
	public partial class RowTradeInf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _trade_date;
		
		private byte _contract_ID;
		
		private System.DateTime _pay_month;
		
		private System.Nullable<double> _price_open;
		
		private System.Nullable<double> _price_hi;
		
		private System.Nullable<double> _price_low;
		
		private System.Nullable<double> _price_close;
		
		private System.Nullable<int> _volume;
		
		private System.Nullable<double> _price_settle;
		
		private System.Nullable<int> _unclosed_volume;
		
		private System.Nullable<double> _last_buy_price;
		
		private System.Nullable<double> _last_sale_price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrade_dateChanging(System.DateTime value);
    partial void Ontrade_dateChanged();
    partial void Oncontract_IDChanging(byte value);
    partial void Oncontract_IDChanged();
    partial void Onpay_monthChanging(System.DateTime value);
    partial void Onpay_monthChanged();
    partial void Onprice_openChanging(System.Nullable<double> value);
    partial void Onprice_openChanged();
    partial void Onprice_hiChanging(System.Nullable<double> value);
    partial void Onprice_hiChanged();
    partial void Onprice_lowChanging(System.Nullable<double> value);
    partial void Onprice_lowChanged();
    partial void Onprice_closeChanging(System.Nullable<double> value);
    partial void Onprice_closeChanged();
    partial void OnvolumeChanging(System.Nullable<int> value);
    partial void OnvolumeChanged();
    partial void Onprice_settleChanging(System.Nullable<double> value);
    partial void Onprice_settleChanged();
    partial void Onunclosed_volumeChanging(System.Nullable<int> value);
    partial void Onunclosed_volumeChanged();
    partial void Onlast_buy_priceChanging(System.Nullable<double> value);
    partial void Onlast_buy_priceChanged();
    partial void Onlast_sale_priceChanging(System.Nullable<double> value);
    partial void Onlast_sale_priceChanged();
    #endregion
		
		public RowTradeInf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trade_date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime trade_date
		{
			get
			{
				return this._trade_date;
			}
			set
			{
				if ((this._trade_date != value))
				{
					this.Ontrade_dateChanging(value);
					this.SendPropertyChanging();
					this._trade_date = value;
					this.SendPropertyChanged("trade_date");
					this.Ontrade_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contract_ID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte contract_ID
		{
			get
			{
				return this._contract_ID;
			}
			set
			{
				if ((this._contract_ID != value))
				{
					this.Oncontract_IDChanging(value);
					this.SendPropertyChanging();
					this._contract_ID = value;
					this.SendPropertyChanged("contract_ID");
					this.Oncontract_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pay_month", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime pay_month
		{
			get
			{
				return this._pay_month;
			}
			set
			{
				if ((this._pay_month != value))
				{
					this.Onpay_monthChanging(value);
					this.SendPropertyChanging();
					this._pay_month = value;
					this.SendPropertyChanged("pay_month");
					this.Onpay_monthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_open", DbType="Float")]
		public System.Nullable<double> price_open
		{
			get
			{
				return this._price_open;
			}
			set
			{
				if ((this._price_open != value))
				{
					this.Onprice_openChanging(value);
					this.SendPropertyChanging();
					this._price_open = value;
					this.SendPropertyChanged("price_open");
					this.Onprice_openChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_hi", DbType="Float")]
		public System.Nullable<double> price_hi
		{
			get
			{
				return this._price_hi;
			}
			set
			{
				if ((this._price_hi != value))
				{
					this.Onprice_hiChanging(value);
					this.SendPropertyChanging();
					this._price_hi = value;
					this.SendPropertyChanged("price_hi");
					this.Onprice_hiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_low", DbType="Float")]
		public System.Nullable<double> price_low
		{
			get
			{
				return this._price_low;
			}
			set
			{
				if ((this._price_low != value))
				{
					this.Onprice_lowChanging(value);
					this.SendPropertyChanging();
					this._price_low = value;
					this.SendPropertyChanged("price_low");
					this.Onprice_lowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_close", DbType="Float")]
		public System.Nullable<double> price_close
		{
			get
			{
				return this._price_close;
			}
			set
			{
				if ((this._price_close != value))
				{
					this.Onprice_closeChanging(value);
					this.SendPropertyChanging();
					this._price_close = value;
					this.SendPropertyChanged("price_close");
					this.Onprice_closeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="Int")]
		public System.Nullable<int> volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_settle", DbType="Float")]
		public System.Nullable<double> price_settle
		{
			get
			{
				return this._price_settle;
			}
			set
			{
				if ((this._price_settle != value))
				{
					this.Onprice_settleChanging(value);
					this.SendPropertyChanging();
					this._price_settle = value;
					this.SendPropertyChanged("price_settle");
					this.Onprice_settleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unclosed_volume", DbType="Int")]
		public System.Nullable<int> unclosed_volume
		{
			get
			{
				return this._unclosed_volume;
			}
			set
			{
				if ((this._unclosed_volume != value))
				{
					this.Onunclosed_volumeChanging(value);
					this.SendPropertyChanging();
					this._unclosed_volume = value;
					this.SendPropertyChanged("unclosed_volume");
					this.Onunclosed_volumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_buy_price", DbType="Float")]
		public System.Nullable<double> last_buy_price
		{
			get
			{
				return this._last_buy_price;
			}
			set
			{
				if ((this._last_buy_price != value))
				{
					this.Onlast_buy_priceChanging(value);
					this.SendPropertyChanging();
					this._last_buy_price = value;
					this.SendPropertyChanged("last_buy_price");
					this.Onlast_buy_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_sale_price", DbType="Float")]
		public System.Nullable<double> last_sale_price
		{
			get
			{
				return this._last_sale_price;
			}
			set
			{
				if ((this._last_sale_price != value))
				{
					this.Onlast_sale_priceChanging(value);
					this.SendPropertyChanging();
					this._last_sale_price = value;
					this.SendPropertyChanged("last_sale_price");
					this.Onlast_sale_priceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FutureCorpX3")]
	public partial class RowCorpX3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _trade_date;
		
		private byte _contract_ID;
		
		private System.Nullable<int> _c1_long_vol;
		
		private System.Nullable<int> _c1_long_moneyK;
		
		private System.Nullable<int> _c1_short_vol;
		
		private System.Nullable<int> _c1_short_moneyK;
		
		private System.Nullable<int> _c1_unclosed_long_vol;
		
		private System.Nullable<int> _c1_unclosed_long_moneyK;
		
		private System.Nullable<int> _c1_unclosed_short_vol;
		
		private System.Nullable<int> _c1_unclosed_short_moneyK;
		
		private System.Nullable<int> _c2_long_vol;
		
		private System.Nullable<int> _c2_long_moneyK;
		
		private System.Nullable<int> _c2_short_vol;
		
		private System.Nullable<int> _c2_short_moneyK;
		
		private System.Nullable<int> _c2_unclosed_long_vol;
		
		private System.Nullable<int> _c2_unclosed_long_moneyK;
		
		private System.Nullable<int> _c2_unclosed_short_vol;
		
		private System.Nullable<int> _c2_unclosed_short_moneyK;
		
		private System.Nullable<int> _c3_long_vol;
		
		private System.Nullable<int> _c3_long_moneyK;
		
		private System.Nullable<int> _c3_short_vol;
		
		private System.Nullable<int> _c3_short_moneyK;
		
		private System.Nullable<int> _c3_unclosed_long_vol;
		
		private System.Nullable<int> _c3_unclosed_long_moneyK;
		
		private System.Nullable<int> _c3_unclosed_short_vol;
		
		private System.Nullable<int> _c3_unclosed_short_moneyK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrade_dateChanging(System.DateTime value);
    partial void Ontrade_dateChanged();
    partial void Oncontract_IDChanging(byte value);
    partial void Oncontract_IDChanged();
    partial void Onc1_long_volChanging(System.Nullable<int> value);
    partial void Onc1_long_volChanged();
    partial void Onc1_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc1_long_moneyKChanged();
    partial void Onc1_short_volChanging(System.Nullable<int> value);
    partial void Onc1_short_volChanged();
    partial void Onc1_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc1_short_moneyKChanged();
    partial void Onc1_unclosed_long_volChanging(System.Nullable<int> value);
    partial void Onc1_unclosed_long_volChanged();
    partial void Onc1_unclosed_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc1_unclosed_long_moneyKChanged();
    partial void Onc1_unclosed_short_volChanging(System.Nullable<int> value);
    partial void Onc1_unclosed_short_volChanged();
    partial void Onc1_unclosed_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc1_unclosed_short_moneyKChanged();
    partial void Onc2_long_volChanging(System.Nullable<int> value);
    partial void Onc2_long_volChanged();
    partial void Onc2_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc2_long_moneyKChanged();
    partial void Onc2_short_volChanging(System.Nullable<int> value);
    partial void Onc2_short_volChanged();
    partial void Onc2_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc2_short_moneyKChanged();
    partial void Onc2_unclosed_long_volChanging(System.Nullable<int> value);
    partial void Onc2_unclosed_long_volChanged();
    partial void Onc2_unclosed_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc2_unclosed_long_moneyKChanged();
    partial void Onc2_unclosed_short_volChanging(System.Nullable<int> value);
    partial void Onc2_unclosed_short_volChanged();
    partial void Onc2_unclosed_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc2_unclosed_short_moneyKChanged();
    partial void Onc3_long_volChanging(System.Nullable<int> value);
    partial void Onc3_long_volChanged();
    partial void Onc3_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc3_long_moneyKChanged();
    partial void Onc3_short_volChanging(System.Nullable<int> value);
    partial void Onc3_short_volChanged();
    partial void Onc3_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc3_short_moneyKChanged();
    partial void Onc3_unclosed_long_volChanging(System.Nullable<int> value);
    partial void Onc3_unclosed_long_volChanged();
    partial void Onc3_unclosed_long_moneyKChanging(System.Nullable<int> value);
    partial void Onc3_unclosed_long_moneyKChanged();
    partial void Onc3_unclosed_short_volChanging(System.Nullable<int> value);
    partial void Onc3_unclosed_short_volChanged();
    partial void Onc3_unclosed_short_moneyKChanging(System.Nullable<int> value);
    partial void Onc3_unclosed_short_moneyKChanged();
    #endregion
		
		public RowCorpX3()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trade_date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime trade_date
		{
			get
			{
				return this._trade_date;
			}
			set
			{
				if ((this._trade_date != value))
				{
					this.Ontrade_dateChanging(value);
					this.SendPropertyChanging();
					this._trade_date = value;
					this.SendPropertyChanged("trade_date");
					this.Ontrade_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contract_ID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte contract_ID
		{
			get
			{
				return this._contract_ID;
			}
			set
			{
				if ((this._contract_ID != value))
				{
					this.Oncontract_IDChanging(value);
					this.SendPropertyChanging();
					this._contract_ID = value;
					this.SendPropertyChanged("contract_ID");
					this.Oncontract_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_long_vol", DbType="Int")]
		public System.Nullable<int> c1_long_vol
		{
			get
			{
				return this._c1_long_vol;
			}
			set
			{
				if ((this._c1_long_vol != value))
				{
					this.Onc1_long_volChanging(value);
					this.SendPropertyChanging();
					this._c1_long_vol = value;
					this.SendPropertyChanged("c1_long_vol");
					this.Onc1_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_long_moneyK", DbType="Int")]
		public System.Nullable<int> c1_long_moneyK
		{
			get
			{
				return this._c1_long_moneyK;
			}
			set
			{
				if ((this._c1_long_moneyK != value))
				{
					this.Onc1_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c1_long_moneyK = value;
					this.SendPropertyChanged("c1_long_moneyK");
					this.Onc1_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_short_vol", DbType="Int")]
		public System.Nullable<int> c1_short_vol
		{
			get
			{
				return this._c1_short_vol;
			}
			set
			{
				if ((this._c1_short_vol != value))
				{
					this.Onc1_short_volChanging(value);
					this.SendPropertyChanging();
					this._c1_short_vol = value;
					this.SendPropertyChanged("c1_short_vol");
					this.Onc1_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_short_moneyK", DbType="Int")]
		public System.Nullable<int> c1_short_moneyK
		{
			get
			{
				return this._c1_short_moneyK;
			}
			set
			{
				if ((this._c1_short_moneyK != value))
				{
					this.Onc1_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c1_short_moneyK = value;
					this.SendPropertyChanged("c1_short_moneyK");
					this.Onc1_short_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_unclosed_long_vol", DbType="Int")]
		public System.Nullable<int> c1_unclosed_long_vol
		{
			get
			{
				return this._c1_unclosed_long_vol;
			}
			set
			{
				if ((this._c1_unclosed_long_vol != value))
				{
					this.Onc1_unclosed_long_volChanging(value);
					this.SendPropertyChanging();
					this._c1_unclosed_long_vol = value;
					this.SendPropertyChanged("c1_unclosed_long_vol");
					this.Onc1_unclosed_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_unclosed_long_moneyK", DbType="Int")]
		public System.Nullable<int> c1_unclosed_long_moneyK
		{
			get
			{
				return this._c1_unclosed_long_moneyK;
			}
			set
			{
				if ((this._c1_unclosed_long_moneyK != value))
				{
					this.Onc1_unclosed_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c1_unclosed_long_moneyK = value;
					this.SendPropertyChanged("c1_unclosed_long_moneyK");
					this.Onc1_unclosed_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_unclosed_short_vol", DbType="Int")]
		public System.Nullable<int> c1_unclosed_short_vol
		{
			get
			{
				return this._c1_unclosed_short_vol;
			}
			set
			{
				if ((this._c1_unclosed_short_vol != value))
				{
					this.Onc1_unclosed_short_volChanging(value);
					this.SendPropertyChanging();
					this._c1_unclosed_short_vol = value;
					this.SendPropertyChanged("c1_unclosed_short_vol");
					this.Onc1_unclosed_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1_unclosed_short_moneyK", DbType="Int")]
		public System.Nullable<int> c1_unclosed_short_moneyK
		{
			get
			{
				return this._c1_unclosed_short_moneyK;
			}
			set
			{
				if ((this._c1_unclosed_short_moneyK != value))
				{
					this.Onc1_unclosed_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c1_unclosed_short_moneyK = value;
					this.SendPropertyChanged("c1_unclosed_short_moneyK");
					this.Onc1_unclosed_short_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_long_vol", DbType="Int")]
		public System.Nullable<int> c2_long_vol
		{
			get
			{
				return this._c2_long_vol;
			}
			set
			{
				if ((this._c2_long_vol != value))
				{
					this.Onc2_long_volChanging(value);
					this.SendPropertyChanging();
					this._c2_long_vol = value;
					this.SendPropertyChanged("c2_long_vol");
					this.Onc2_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_long_moneyK", DbType="Int")]
		public System.Nullable<int> c2_long_moneyK
		{
			get
			{
				return this._c2_long_moneyK;
			}
			set
			{
				if ((this._c2_long_moneyK != value))
				{
					this.Onc2_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c2_long_moneyK = value;
					this.SendPropertyChanged("c2_long_moneyK");
					this.Onc2_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_short_vol", DbType="Int")]
		public System.Nullable<int> c2_short_vol
		{
			get
			{
				return this._c2_short_vol;
			}
			set
			{
				if ((this._c2_short_vol != value))
				{
					this.Onc2_short_volChanging(value);
					this.SendPropertyChanging();
					this._c2_short_vol = value;
					this.SendPropertyChanged("c2_short_vol");
					this.Onc2_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_short_moneyK", DbType="Int")]
		public System.Nullable<int> c2_short_moneyK
		{
			get
			{
				return this._c2_short_moneyK;
			}
			set
			{
				if ((this._c2_short_moneyK != value))
				{
					this.Onc2_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c2_short_moneyK = value;
					this.SendPropertyChanged("c2_short_moneyK");
					this.Onc2_short_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_unclosed_long_vol", DbType="Int")]
		public System.Nullable<int> c2_unclosed_long_vol
		{
			get
			{
				return this._c2_unclosed_long_vol;
			}
			set
			{
				if ((this._c2_unclosed_long_vol != value))
				{
					this.Onc2_unclosed_long_volChanging(value);
					this.SendPropertyChanging();
					this._c2_unclosed_long_vol = value;
					this.SendPropertyChanged("c2_unclosed_long_vol");
					this.Onc2_unclosed_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_unclosed_long_moneyK", DbType="Int")]
		public System.Nullable<int> c2_unclosed_long_moneyK
		{
			get
			{
				return this._c2_unclosed_long_moneyK;
			}
			set
			{
				if ((this._c2_unclosed_long_moneyK != value))
				{
					this.Onc2_unclosed_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c2_unclosed_long_moneyK = value;
					this.SendPropertyChanged("c2_unclosed_long_moneyK");
					this.Onc2_unclosed_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_unclosed_short_vol", DbType="Int")]
		public System.Nullable<int> c2_unclosed_short_vol
		{
			get
			{
				return this._c2_unclosed_short_vol;
			}
			set
			{
				if ((this._c2_unclosed_short_vol != value))
				{
					this.Onc2_unclosed_short_volChanging(value);
					this.SendPropertyChanging();
					this._c2_unclosed_short_vol = value;
					this.SendPropertyChanged("c2_unclosed_short_vol");
					this.Onc2_unclosed_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2_unclosed_short_moneyK", DbType="Int")]
		public System.Nullable<int> c2_unclosed_short_moneyK
		{
			get
			{
				return this._c2_unclosed_short_moneyK;
			}
			set
			{
				if ((this._c2_unclosed_short_moneyK != value))
				{
					this.Onc2_unclosed_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c2_unclosed_short_moneyK = value;
					this.SendPropertyChanged("c2_unclosed_short_moneyK");
					this.Onc2_unclosed_short_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_long_vol", DbType="Int")]
		public System.Nullable<int> c3_long_vol
		{
			get
			{
				return this._c3_long_vol;
			}
			set
			{
				if ((this._c3_long_vol != value))
				{
					this.Onc3_long_volChanging(value);
					this.SendPropertyChanging();
					this._c3_long_vol = value;
					this.SendPropertyChanged("c3_long_vol");
					this.Onc3_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_long_moneyK", DbType="Int")]
		public System.Nullable<int> c3_long_moneyK
		{
			get
			{
				return this._c3_long_moneyK;
			}
			set
			{
				if ((this._c3_long_moneyK != value))
				{
					this.Onc3_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c3_long_moneyK = value;
					this.SendPropertyChanged("c3_long_moneyK");
					this.Onc3_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_short_vol", DbType="Int")]
		public System.Nullable<int> c3_short_vol
		{
			get
			{
				return this._c3_short_vol;
			}
			set
			{
				if ((this._c3_short_vol != value))
				{
					this.Onc3_short_volChanging(value);
					this.SendPropertyChanging();
					this._c3_short_vol = value;
					this.SendPropertyChanged("c3_short_vol");
					this.Onc3_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_short_moneyK", DbType="Int")]
		public System.Nullable<int> c3_short_moneyK
		{
			get
			{
				return this._c3_short_moneyK;
			}
			set
			{
				if ((this._c3_short_moneyK != value))
				{
					this.Onc3_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c3_short_moneyK = value;
					this.SendPropertyChanged("c3_short_moneyK");
					this.Onc3_short_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_unclosed_long_vol", DbType="Int")]
		public System.Nullable<int> c3_unclosed_long_vol
		{
			get
			{
				return this._c3_unclosed_long_vol;
			}
			set
			{
				if ((this._c3_unclosed_long_vol != value))
				{
					this.Onc3_unclosed_long_volChanging(value);
					this.SendPropertyChanging();
					this._c3_unclosed_long_vol = value;
					this.SendPropertyChanged("c3_unclosed_long_vol");
					this.Onc3_unclosed_long_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_unclosed_long_moneyK", DbType="Int")]
		public System.Nullable<int> c3_unclosed_long_moneyK
		{
			get
			{
				return this._c3_unclosed_long_moneyK;
			}
			set
			{
				if ((this._c3_unclosed_long_moneyK != value))
				{
					this.Onc3_unclosed_long_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c3_unclosed_long_moneyK = value;
					this.SendPropertyChanged("c3_unclosed_long_moneyK");
					this.Onc3_unclosed_long_moneyKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_unclosed_short_vol", DbType="Int")]
		public System.Nullable<int> c3_unclosed_short_vol
		{
			get
			{
				return this._c3_unclosed_short_vol;
			}
			set
			{
				if ((this._c3_unclosed_short_vol != value))
				{
					this.Onc3_unclosed_short_volChanging(value);
					this.SendPropertyChanging();
					this._c3_unclosed_short_vol = value;
					this.SendPropertyChanged("c3_unclosed_short_vol");
					this.Onc3_unclosed_short_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3_unclosed_short_moneyK", DbType="Int")]
		public System.Nullable<int> c3_unclosed_short_moneyK
		{
			get
			{
				return this._c3_unclosed_short_moneyK;
			}
			set
			{
				if ((this._c3_unclosed_short_moneyK != value))
				{
					this.Onc3_unclosed_short_moneyKChanging(value);
					this.SendPropertyChanging();
					this._c3_unclosed_short_moneyK = value;
					this.SendPropertyChanged("c3_unclosed_short_moneyK");
					this.Onc3_unclosed_short_moneyKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FutureBigTraderUnclosedVol")]
	public partial class RowBigTraderUnclosedVol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _trade_date;
		
		private byte _contract_ID;
		
		private System.Nullable<int> _top5_buy_vol;
		
		private System.Nullable<int> _top5_sell_vol;
		
		private System.Nullable<int> _top10_buy_vol;
		
		private System.Nullable<int> _top10_sell_vol;
		
		private System.Nullable<int> _top5corp_buy_vol;
		
		private System.Nullable<int> _top5corp_sell_vol;
		
		private System.Nullable<int> _top10corp_buy_vol;
		
		private System.Nullable<int> _top10corp_sell_vol;
		
		private System.Nullable<int> _near_top5_buy_vol;
		
		private System.Nullable<int> _near_top5_sell_vol;
		
		private System.Nullable<int> _near_top10_buy_vol;
		
		private System.Nullable<int> _near_top10_sell_vol;
		
		private System.Nullable<int> _near_top5corp_buy_vol;
		
		private System.Nullable<int> _near_top5corp_sell_vol;
		
		private System.Nullable<int> _near_top10corp_buy_vol;
		
		private System.Nullable<int> _near_top10corp_sell_vol;
		
		private System.Nullable<int> _market_vol;
		
		private System.Nullable<int> _near_market_vol;
		
		private System.Nullable<int> _week_market_vol;
		
		private System.Nullable<int> _week_top5_buy_vol;
		
		private System.Nullable<int> _week_top5_sell_vol;
		
		private System.Nullable<int> _week_top10_buy_vol;
		
		private System.Nullable<int> _week_top10_sell_vol;
		
		private System.Nullable<int> _week_top5corp_buy_vol;
		
		private System.Nullable<int> _week_top5corp_sell_vol;
		
		private System.Nullable<int> _week_top10corp_buy_vol;
		
		private System.Nullable<int> _week_top10corp_sell_vol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontrade_dateChanging(System.DateTime value);
    partial void Ontrade_dateChanged();
    partial void Oncontract_IDChanging(byte value);
    partial void Oncontract_IDChanged();
    partial void Ontop5_buy_volChanging(System.Nullable<int> value);
    partial void Ontop5_buy_volChanged();
    partial void Ontop5_sell_volChanging(System.Nullable<int> value);
    partial void Ontop5_sell_volChanged();
    partial void Ontop10_buy_volChanging(System.Nullable<int> value);
    partial void Ontop10_buy_volChanged();
    partial void Ontop10_sell_volChanging(System.Nullable<int> value);
    partial void Ontop10_sell_volChanged();
    partial void Ontop5corp_buy_volChanging(System.Nullable<int> value);
    partial void Ontop5corp_buy_volChanged();
    partial void Ontop5corp_sell_volChanging(System.Nullable<int> value);
    partial void Ontop5corp_sell_volChanged();
    partial void Ontop10corp_buy_volChanging(System.Nullable<int> value);
    partial void Ontop10corp_buy_volChanged();
    partial void Ontop10corp_sell_volChanging(System.Nullable<int> value);
    partial void Ontop10corp_sell_volChanged();
    partial void Onnear_top5_buy_volChanging(System.Nullable<int> value);
    partial void Onnear_top5_buy_volChanged();
    partial void Onnear_top5_sell_volChanging(System.Nullable<int> value);
    partial void Onnear_top5_sell_volChanged();
    partial void Onnear_top10_buy_volChanging(System.Nullable<int> value);
    partial void Onnear_top10_buy_volChanged();
    partial void Onnear_top10_sell_volChanging(System.Nullable<int> value);
    partial void Onnear_top10_sell_volChanged();
    partial void Onnear_top5corp_buy_volChanging(System.Nullable<int> value);
    partial void Onnear_top5corp_buy_volChanged();
    partial void Onnear_top5corp_sell_volChanging(System.Nullable<int> value);
    partial void Onnear_top5corp_sell_volChanged();
    partial void Onnear_top10corp_buy_volChanging(System.Nullable<int> value);
    partial void Onnear_top10corp_buy_volChanged();
    partial void Onnear_top10corp_sell_volChanging(System.Nullable<int> value);
    partial void Onnear_top10corp_sell_volChanged();
    partial void Onmarket_volChanging(System.Nullable<int> value);
    partial void Onmarket_volChanged();
    partial void Onnear_market_volChanging(System.Nullable<int> value);
    partial void Onnear_market_volChanged();
    partial void Onweek_market_volChanging(System.Nullable<int> value);
    partial void Onweek_market_volChanged();
    partial void Onweek_top5_buy_volChanging(System.Nullable<int> value);
    partial void Onweek_top5_buy_volChanged();
    partial void Onweek_top5_sell_volChanging(System.Nullable<int> value);
    partial void Onweek_top5_sell_volChanged();
    partial void Onweek_top10_buy_volChanging(System.Nullable<int> value);
    partial void Onweek_top10_buy_volChanged();
    partial void Onweek_top10_sell_volChanging(System.Nullable<int> value);
    partial void Onweek_top10_sell_volChanged();
    partial void Onweek_top5corp_buy_volChanging(System.Nullable<int> value);
    partial void Onweek_top5corp_buy_volChanged();
    partial void Onweek_top5corp_sell_volChanging(System.Nullable<int> value);
    partial void Onweek_top5corp_sell_volChanged();
    partial void Onweek_top10corp_buy_volChanging(System.Nullable<int> value);
    partial void Onweek_top10corp_buy_volChanged();
    partial void Onweek_top10corp_sell_volChanging(System.Nullable<int> value);
    partial void Onweek_top10corp_sell_volChanged();
    #endregion
		
		public RowBigTraderUnclosedVol()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trade_date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime trade_date
		{
			get
			{
				return this._trade_date;
			}
			set
			{
				if ((this._trade_date != value))
				{
					this.Ontrade_dateChanging(value);
					this.SendPropertyChanging();
					this._trade_date = value;
					this.SendPropertyChanged("trade_date");
					this.Ontrade_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contract_ID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte contract_ID
		{
			get
			{
				return this._contract_ID;
			}
			set
			{
				if ((this._contract_ID != value))
				{
					this.Oncontract_IDChanging(value);
					this.SendPropertyChanging();
					this._contract_ID = value;
					this.SendPropertyChanged("contract_ID");
					this.Oncontract_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top5_buy_vol", DbType="Int")]
		public System.Nullable<int> top5_buy_vol
		{
			get
			{
				return this._top5_buy_vol;
			}
			set
			{
				if ((this._top5_buy_vol != value))
				{
					this.Ontop5_buy_volChanging(value);
					this.SendPropertyChanging();
					this._top5_buy_vol = value;
					this.SendPropertyChanged("top5_buy_vol");
					this.Ontop5_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top5_sell_vol", DbType="Int")]
		public System.Nullable<int> top5_sell_vol
		{
			get
			{
				return this._top5_sell_vol;
			}
			set
			{
				if ((this._top5_sell_vol != value))
				{
					this.Ontop5_sell_volChanging(value);
					this.SendPropertyChanging();
					this._top5_sell_vol = value;
					this.SendPropertyChanged("top5_sell_vol");
					this.Ontop5_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top10_buy_vol", DbType="Int")]
		public System.Nullable<int> top10_buy_vol
		{
			get
			{
				return this._top10_buy_vol;
			}
			set
			{
				if ((this._top10_buy_vol != value))
				{
					this.Ontop10_buy_volChanging(value);
					this.SendPropertyChanging();
					this._top10_buy_vol = value;
					this.SendPropertyChanged("top10_buy_vol");
					this.Ontop10_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top10_sell_vol", DbType="Int")]
		public System.Nullable<int> top10_sell_vol
		{
			get
			{
				return this._top10_sell_vol;
			}
			set
			{
				if ((this._top10_sell_vol != value))
				{
					this.Ontop10_sell_volChanging(value);
					this.SendPropertyChanging();
					this._top10_sell_vol = value;
					this.SendPropertyChanged("top10_sell_vol");
					this.Ontop10_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top5corp_buy_vol", DbType="Int")]
		public System.Nullable<int> top5corp_buy_vol
		{
			get
			{
				return this._top5corp_buy_vol;
			}
			set
			{
				if ((this._top5corp_buy_vol != value))
				{
					this.Ontop5corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._top5corp_buy_vol = value;
					this.SendPropertyChanged("top5corp_buy_vol");
					this.Ontop5corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top5corp_sell_vol", DbType="Int")]
		public System.Nullable<int> top5corp_sell_vol
		{
			get
			{
				return this._top5corp_sell_vol;
			}
			set
			{
				if ((this._top5corp_sell_vol != value))
				{
					this.Ontop5corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._top5corp_sell_vol = value;
					this.SendPropertyChanged("top5corp_sell_vol");
					this.Ontop5corp_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top10corp_buy_vol", DbType="Int")]
		public System.Nullable<int> top10corp_buy_vol
		{
			get
			{
				return this._top10corp_buy_vol;
			}
			set
			{
				if ((this._top10corp_buy_vol != value))
				{
					this.Ontop10corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._top10corp_buy_vol = value;
					this.SendPropertyChanged("top10corp_buy_vol");
					this.Ontop10corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top10corp_sell_vol", DbType="Int")]
		public System.Nullable<int> top10corp_sell_vol
		{
			get
			{
				return this._top10corp_sell_vol;
			}
			set
			{
				if ((this._top10corp_sell_vol != value))
				{
					this.Ontop10corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._top10corp_sell_vol = value;
					this.SendPropertyChanged("top10corp_sell_vol");
					this.Ontop10corp_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top5_buy_vol", DbType="Int")]
		public System.Nullable<int> near_top5_buy_vol
		{
			get
			{
				return this._near_top5_buy_vol;
			}
			set
			{
				if ((this._near_top5_buy_vol != value))
				{
					this.Onnear_top5_buy_volChanging(value);
					this.SendPropertyChanging();
					this._near_top5_buy_vol = value;
					this.SendPropertyChanged("near_top5_buy_vol");
					this.Onnear_top5_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top5_sell_vol", DbType="Int")]
		public System.Nullable<int> near_top5_sell_vol
		{
			get
			{
				return this._near_top5_sell_vol;
			}
			set
			{
				if ((this._near_top5_sell_vol != value))
				{
					this.Onnear_top5_sell_volChanging(value);
					this.SendPropertyChanging();
					this._near_top5_sell_vol = value;
					this.SendPropertyChanged("near_top5_sell_vol");
					this.Onnear_top5_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top10_buy_vol", DbType="Int")]
		public System.Nullable<int> near_top10_buy_vol
		{
			get
			{
				return this._near_top10_buy_vol;
			}
			set
			{
				if ((this._near_top10_buy_vol != value))
				{
					this.Onnear_top10_buy_volChanging(value);
					this.SendPropertyChanging();
					this._near_top10_buy_vol = value;
					this.SendPropertyChanged("near_top10_buy_vol");
					this.Onnear_top10_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top10_sell_vol", DbType="Int")]
		public System.Nullable<int> near_top10_sell_vol
		{
			get
			{
				return this._near_top10_sell_vol;
			}
			set
			{
				if ((this._near_top10_sell_vol != value))
				{
					this.Onnear_top10_sell_volChanging(value);
					this.SendPropertyChanging();
					this._near_top10_sell_vol = value;
					this.SendPropertyChanged("near_top10_sell_vol");
					this.Onnear_top10_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top5corp_buy_vol", DbType="Int")]
		public System.Nullable<int> near_top5corp_buy_vol
		{
			get
			{
				return this._near_top5corp_buy_vol;
			}
			set
			{
				if ((this._near_top5corp_buy_vol != value))
				{
					this.Onnear_top5corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._near_top5corp_buy_vol = value;
					this.SendPropertyChanged("near_top5corp_buy_vol");
					this.Onnear_top5corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top5corp_sell_vol", DbType="Int")]
		public System.Nullable<int> near_top5corp_sell_vol
		{
			get
			{
				return this._near_top5corp_sell_vol;
			}
			set
			{
				if ((this._near_top5corp_sell_vol != value))
				{
					this.Onnear_top5corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._near_top5corp_sell_vol = value;
					this.SendPropertyChanged("near_top5corp_sell_vol");
					this.Onnear_top5corp_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top10corp_buy_vol", DbType="Int")]
		public System.Nullable<int> near_top10corp_buy_vol
		{
			get
			{
				return this._near_top10corp_buy_vol;
			}
			set
			{
				if ((this._near_top10corp_buy_vol != value))
				{
					this.Onnear_top10corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._near_top10corp_buy_vol = value;
					this.SendPropertyChanged("near_top10corp_buy_vol");
					this.Onnear_top10corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_top10corp_sell_vol", DbType="Int")]
		public System.Nullable<int> near_top10corp_sell_vol
		{
			get
			{
				return this._near_top10corp_sell_vol;
			}
			set
			{
				if ((this._near_top10corp_sell_vol != value))
				{
					this.Onnear_top10corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._near_top10corp_sell_vol = value;
					this.SendPropertyChanged("near_top10corp_sell_vol");
					this.Onnear_top10corp_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_market_vol", DbType="Int")]
		public System.Nullable<int> market_vol
		{
			get
			{
				return this._market_vol;
			}
			set
			{
				if ((this._market_vol != value))
				{
					this.Onmarket_volChanging(value);
					this.SendPropertyChanging();
					this._market_vol = value;
					this.SendPropertyChanged("market_vol");
					this.Onmarket_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_near_market_vol", DbType="Int")]
		public System.Nullable<int> near_market_vol
		{
			get
			{
				return this._near_market_vol;
			}
			set
			{
				if ((this._near_market_vol != value))
				{
					this.Onnear_market_volChanging(value);
					this.SendPropertyChanging();
					this._near_market_vol = value;
					this.SendPropertyChanged("near_market_vol");
					this.Onnear_market_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_market_vol", DbType="Int")]
		public System.Nullable<int> week_market_vol
		{
			get
			{
				return this._week_market_vol;
			}
			set
			{
				if ((this._week_market_vol != value))
				{
					this.Onweek_market_volChanging(value);
					this.SendPropertyChanging();
					this._week_market_vol = value;
					this.SendPropertyChanged("week_market_vol");
					this.Onweek_market_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top5_buy_vol", DbType="Int")]
		public System.Nullable<int> week_top5_buy_vol
		{
			get
			{
				return this._week_top5_buy_vol;
			}
			set
			{
				if ((this._week_top5_buy_vol != value))
				{
					this.Onweek_top5_buy_volChanging(value);
					this.SendPropertyChanging();
					this._week_top5_buy_vol = value;
					this.SendPropertyChanged("week_top5_buy_vol");
					this.Onweek_top5_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top5_sell_vol", DbType="Int")]
		public System.Nullable<int> week_top5_sell_vol
		{
			get
			{
				return this._week_top5_sell_vol;
			}
			set
			{
				if ((this._week_top5_sell_vol != value))
				{
					this.Onweek_top5_sell_volChanging(value);
					this.SendPropertyChanging();
					this._week_top5_sell_vol = value;
					this.SendPropertyChanged("week_top5_sell_vol");
					this.Onweek_top5_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top10_buy_vol", DbType="Int")]
		public System.Nullable<int> week_top10_buy_vol
		{
			get
			{
				return this._week_top10_buy_vol;
			}
			set
			{
				if ((this._week_top10_buy_vol != value))
				{
					this.Onweek_top10_buy_volChanging(value);
					this.SendPropertyChanging();
					this._week_top10_buy_vol = value;
					this.SendPropertyChanged("week_top10_buy_vol");
					this.Onweek_top10_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top10_sell_vol", DbType="Int")]
		public System.Nullable<int> week_top10_sell_vol
		{
			get
			{
				return this._week_top10_sell_vol;
			}
			set
			{
				if ((this._week_top10_sell_vol != value))
				{
					this.Onweek_top10_sell_volChanging(value);
					this.SendPropertyChanging();
					this._week_top10_sell_vol = value;
					this.SendPropertyChanged("week_top10_sell_vol");
					this.Onweek_top10_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top5corp_buy_vol", DbType="Int")]
		public System.Nullable<int> week_top5corp_buy_vol
		{
			get
			{
				return this._week_top5corp_buy_vol;
			}
			set
			{
				if ((this._week_top5corp_buy_vol != value))
				{
					this.Onweek_top5corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._week_top5corp_buy_vol = value;
					this.SendPropertyChanged("week_top5corp_buy_vol");
					this.Onweek_top5corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top5corp_sell_vol", DbType="Int")]
		public System.Nullable<int> week_top5corp_sell_vol
		{
			get
			{
				return this._week_top5corp_sell_vol;
			}
			set
			{
				if ((this._week_top5corp_sell_vol != value))
				{
					this.Onweek_top5corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._week_top5corp_sell_vol = value;
					this.SendPropertyChanged("week_top5corp_sell_vol");
					this.Onweek_top5corp_sell_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top10corp_buy_vol", DbType="Int")]
		public System.Nullable<int> week_top10corp_buy_vol
		{
			get
			{
				return this._week_top10corp_buy_vol;
			}
			set
			{
				if ((this._week_top10corp_buy_vol != value))
				{
					this.Onweek_top10corp_buy_volChanging(value);
					this.SendPropertyChanging();
					this._week_top10corp_buy_vol = value;
					this.SendPropertyChanged("week_top10corp_buy_vol");
					this.Onweek_top10corp_buy_volChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week_top10corp_sell_vol", DbType="Int")]
		public System.Nullable<int> week_top10corp_sell_vol
		{
			get
			{
				return this._week_top10corp_sell_vol;
			}
			set
			{
				if ((this._week_top10corp_sell_vol != value))
				{
					this.Onweek_top10corp_sell_volChanging(value);
					this.SendPropertyChanging();
					this._week_top10corp_sell_vol = value;
					this.SendPropertyChanged("week_top10corp_sell_vol");
					this.Onweek_top10corp_sell_volChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
